name,code,country,lat,lon,elev,style,rwdir,rwlen,freq,desc
* This short CUP file is made up from the WAYPOINTS variable inside aerofiles.seeyou.Reader
* furthermore it contains a task at the end
"Meiersberg","MEIER",DE,5117.983N,00657.383E,164m,4,130,800m,130.125,"Flugplatz"
"Manosque Pont D9","MANOSQ",FR,4348.267N,00549.467E,295m,14,,,,"PONT D907"
"MarcouX Champ 8","MARCO2",FR,4407.650N,00617.233E,694m,3,130,250m,,"Landefeld"
"Sydney Nsw Kinss","SYDNE",AU,3356.767S,15110.633E,6m,5,160,3950m,120.500,"Flugplatz"
"Ulm H Bf","ULMHBF",DE,4823.967N,00958.983E,480m,1,,,,"BAHNHOF"
"Vettweiss Soller","VETTW2",DE,5044.850N,00634.033E,159m,3,150,380m,120.975,"Landefeld"
"Weisweiler Kw 10","WEISWE",DE,5050.383N,00619.367E,144m,15,,,,"KW1011FT"
"Eddln0 Eddl N P","EDDLN0",DE,5124.400N,00644.900E,28m,1,,,,"EDDLN P"
-----Related Tasks-----
"3 turnpoints","Meiersberg","Meiersberg","Vettweiss Soller","Weisweiler Kw 10","Eddln0 Eddl N P","Meiersberg","Meiersberg"
Options,TaskTime=03:00:00,WpDis=True,MinDis=True,RandomOrder=False,MaxPts=13
ObsZone=0,Style=2,R1=2500m,Line=1
ObsZone=1,Style=1,R1=500m,A1=180
ObsZone=2,Style=1,R1=500m,A1=180
ObsZone=3,Style=1,R1=2000m,A1=180
ObsZone=4,Style=3,R1=500m,Line=1