User's Guide
------------

This part of the documentation, which is mostly prose, begins with some
background information about Flask, then focuses on step-by-step
instructions for web development with Flask.

.. toctree::
   :maxdepth: 2

   installation
   igc_file_writing

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api/index

Additional Notes
----------------

Legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 1

   changelog
   license
