User's Guide
------------

This part of the documentation explains typical use cases with `aerofiles`.

.. toctree::
   :maxdepth: 2

   installation
   guide/igc-writing

API Reference
-------------

If you are looking for information on a specific function, class or
method, this part of the documentation is for you.

.. toctree::
   :maxdepth: 2

   api/index

Additional Notes
----------------

Legal information and changelog are here for the interested.

.. toctree::
   :maxdepth: 1

   changelog
   license
